# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenary',
            name='public',
            field=models.BooleanField(default=False, help_text='Check to display this event on the public events list'),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='breakouts_open',
            field=models.BooleanField(default=False, help_text='Check to allow people to join breakouts associated with this plenary'),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='history',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='open',
            field=models.BooleanField(default=False, help_text='Check to allow people to chat in this plenary'),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='slug',
            field=models.SlugField(help_text='Short name for URL'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(help_text='Short name for URL'),
        ),
    ]
