# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0002_auto_20160330_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plenary',
            options={'verbose_name_plural': 'plenaries'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='plenary',
            name='public',
            field=models.BooleanField(default=False, help_text='Check to display this plenary on the public events list'),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', help_text='Default time zone to display times in.'),
        ),
        migrations.AlterField(
            model_name='series',
            name='end_date',
            field=models.DateTimeField(verbose_name='End date (UTC)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date (UTC)'),
        ),
        migrations.AlterField(
            model_name='series',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', help_text='Default time zone to display times in.'),
        ),
    ]
