# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plenaries', '0003_auto_20160331_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Chat message',
                'verbose_name_plural': 'Chat messages',
            },
        ),
        migrations.AlterModelOptions(
            name='plenary',
            options={'verbose_name': 'Plenary', 'verbose_name_plural': 'Plenaries'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='plenary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plenaries'),
        ),
        migrations.AddField(
            model_name='plenary',
            name='session_mode',
            field=models.CharField(choices=[('admin', 'Admin controlled'), ('user', 'Participant proposed'), ('randomized', 'Randomized breakouts')], default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='plenary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plenaries.Plenary'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
