# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0004_auto_20160422_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created'], 'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
        migrations.RenameField(
            model_name='plenary',
            old_name='session_mode',
            new_name='breakout_mode',
        ),
    ]
