# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0005_auto_20160509_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
