# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0006_chatmessage_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenary',
            name='breakout_mode',
            field=models.CharField(choices=[('admin', 'Admin controlled'), ('user', 'Participant proposed'), ('randomized', 'Randomized breakouts')], default='admin', max_length=20),
        ),
    ]
