# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0008_plenary_randomized_max_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plenary',
            old_name='randomized_max_attendees',
            new_name='random_max_attendees',
        ),
        migrations.AlterField(
            model_name='plenary',
            name='breakout_mode',
            field=models.CharField(choices=[('admin', 'Admin controlled'), ('user', 'Participant proposed'), ('random', 'Random breakouts')], default='admin', max_length=20),
        ),
    ]
