# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 20:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0009_auto_20160810_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenary',
            name='whiteboard',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
