# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import reunhangout.utils


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0010_auto_20160826_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenary',
            name='webrtc_id',
            field=models.CharField(default=reunhangout.utils.random_webrtc_id, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='whiteboard',
            field=models.TextField(blank=True, default=''),
        ),
    ]
