# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 22:45
from __future__ import unicode_literals

from django.db import migrations
from reunhangout.utils import random_webrtc_id

def re_randomize_webrtc_ids(apps, schema_editor):
    Plenary = apps.get_model("plenaries", "Plenary")
    for p in Plenary.objects.all():
        p.webrtc_id = random_webrtc_id()
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0011_auto_20160905_2243'),
    ]

    operations = [
        migrations.RunPython(re_randomize_webrtc_ids)
    ]
