# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plenaries', '0013_auto_20160905_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenary',
            name='live_participants',
            field=models.ManyToManyField(related_name='plenaries_participating_live', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='whiteboard',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
    ]
