# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0015_auto_20161005_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenary',
            name='whiteboard',
            field=models.TextField(blank=True, default=''),
        ),
    ]
