# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0016_auto_20161128_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
