# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plenaries', '0019_auto_20170114_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentions',
            field=models.ManyToManyField(related_name='mentioned_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
