# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0021_plenary_jitsi_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenary',
            name='max_participants',
            field=models.PositiveIntegerField(default=200, help_text='Maximum number of connections. Set to 0 for no limit.'),
        ),
    ]
