# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0022_plenary_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenary',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of connections. Set to 0 for no limit.'),
        ),
    ]
