# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0023_auto_20170315_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenary',
            name='wrapup_emails',
            field=models.BooleanField(default=False, help_text='Enable wrap-up emails? Enabling will require participants to set their contact preferences. Wrap-up emails can only be initiated by Unhangout staff.'),
        ),
        migrations.AlterField(
            model_name='plenary',
            name='whiteboard',
            field=models.TextField(blank=True, default='Welcome to our unhangout! Say hi 👋 in the chat.'),
        ),
    ]
