# Generated by Django 2.2.15 on 2020-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plenaries', '0025_plenary_etherpad_initial_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plenary',
            name='random_max_attendees',
        ),
    ]
