# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional page title; used when component represents a full page (e.g. terms/license)', max_length=255)),
                ('html', models.TextField()),
            ],
        ),
    ]
