# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('change_auth', 'change auth'), ('change_breakout_vote', 'change breakout vote'), ('change_embeds', 'change embeds'), ('close_breakouts', 'close breakouts'), ('close_plenary', 'close plenary'), ('error', 'error'), ('join_breakout', 'join breakout'), ('join_plenary', 'join plenary'), ('leave_breakout', 'leave breakout'), ('leave_plenary', 'leave plenary'), ('message_breakouts', 'message breakouts'), ('open_breakouts', 'open breakouts'), ('open_plenary', 'open plenary'), ('plenary_chat', 'plenary chat'), ('propose_breakout', 'propose breakout'), ('start_play_for_all', 'start play for all'), ('stop_play_for_all', 'stop play for all')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
