# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20160817_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('change_auth', 'change auth'), ('change_breakout_vote', 'change breakout vote'), ('change_contact_card', 'change contact card'), ('change_embeds', 'change embeds'), ('close_breakouts', 'close breakouts'), ('close_plenary', 'close plenary'), ('error', 'error'), ('join_breakout', 'join breakout'), ('join_plenary', 'join plenary'), ('leave_breakout', 'leave breakout'), ('leave_plenary', 'leave plenary'), ('message_breakouts', 'message breakouts'), ('open_breakouts', 'open breakouts'), ('open_plenary', 'open plenary'), ('plenary_chat', 'plenary chat'), ('propose_breakout', 'propose breakout'), ('start_play_for_all', 'start play for all'), ('stop_play_for_all', 'stop play for all')], max_length=20),
        ),
    ]
