# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lurker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='lurkers',
            field=models.ManyToManyField(to='rooms.Lurker'),
        ),
    ]
