# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20160726_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='path',
            new_name='channel_name',
        ),
        migrations.AddField(
            model_name='connection',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='connection',
            name='channel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('room', 'channel_name')]),
        ),
    ]
