# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('start_time_clock', models.DateTimeField()),
                ('start_time_index', models.IntegerField()),
                ('current_time_index', models.IntegerField(default=0)),
            ],
        ),
    ]
