# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosync',
            name='room_name',
        ),
        migrations.AddField(
            model_name='videosync',
            name='channel_group_name',
            field=models.CharField(default=None, help_text='Name of the channel group to broadcast to', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videosync',
            name='sync_id',
            field=models.CharField(default=None, help_text='Unique name for the video container we are syncing', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
