# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160330_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='share_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
