# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160930_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='share_info',
        ),
        migrations.AddField(
            model_name='user',
            name='receive_wrapup_email',
            field=models.NullBooleanField(help_text='Receive wrap-up emails after events?'),
        ),
        migrations.AddField(
            model_name='user',
            name='share_email',
            field=models.BooleanField(default=False, help_text='Do you want to share your email address with others who participate in events with you?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_profile',
            field=models.CharField(blank=True, default=None, help_text='Shared with co-participants in events', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, default=None, help_text='Shared with co-participants in events', max_length=100, null=True, unique=True),
        ),
    ]
