# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170831_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='receive_wrapup_email',
            new_name='receive_wrapup_emails',
        ),
    ]
