# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170831_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_handle',
            new_name='contact_card_twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share_email',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_card_email',
            field=models.EmailField(blank=True, help_text='Shared with co-participants in events', max_length=254, null=True),
        ),
    ]
