# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170905_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('wrapup_email', 'Wrapup Email')], max_length=50)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.CharField(help_text='Comma separated list of email addresses', max_length=255)),
                ('subject', models.TextField()),
                ('body_txt', models.TextField()),
                ('body_html', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.NullBooleanField(default=None)),
                ('opens', jsonfield.fields.JSONField(default=list)),
                ('clicks', jsonfield.fields.JSONField(default=list)),
                ('deliveries', jsonfield.fields.JSONField(default=list)),
                ('failures', jsonfield.fields.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailnotification',
            unique_together=set([('user', 'event_key')]),
        ),
    ]
