# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 14:54
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170928_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube_credentials',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
