# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plenaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('max_attendees', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('activities', jsonfield.fields.JSONField()),
                ('history', jsonfield.fields.JSONField()),
                ('is_hoa', models.BooleanField(default=False)),
                ('is_proposal', models.BooleanField(default=False)),
                ('google_hoa', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleHangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='breakout',
            name='google_hangout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakouts.GoogleHangout'),
        ),
        migrations.AddField(
            model_name='breakout',
            name='plenary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plenaries.Plenary'),
        ),
        migrations.AddField(
            model_name='breakout',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_breakouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakout',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_on_breakouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
