# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakout',
            name='activities',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakout',
            name='history',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakout',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
