# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0002_auto_20160330_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakout',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
