# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import reunhangout.utils


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0004_auto_20160727_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakout',
            name='google_hangout',
        ),
        migrations.RemoveField(
            model_name='breakout',
            name='google_hoa',
        ),
        migrations.AddField(
            model_name='breakout',
            name='webrtc_id',
            field=models.CharField(default=reunhangout.utils.random_webrtc_id, editable=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='GoogleHangout',
        ),
    ]
