# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-26 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breakouts', '0010_auto_20170124_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_data', models.TextField(blank=True, default='')),
                ('additional_info', models.TextField(blank=True, default='')),
                ('breakout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakouts.Breakout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
