# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0011_errorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakout',
            name='max_attendees',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
