# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0012_auto_20170906_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakout',
            name='etherpad_initial_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
