# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0013_breakout_etherpad_initial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakout',
            name='slug',
            field=models.SlugField(blank=True, max_length=90),
        ),
    ]
