# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0014_auto_20171009_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakout',
            name='active',
            field=models.BooleanField(default=True, help_text='Hidden and joinable if unchecked'),
        ),
    ]
