# Generated by Django 2.2.14 on 2020-08-05 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakouts', '0016_breakout_enable_speaker_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakout',
            name='max_attendees',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
