---
- hosts: all
  vars_files:
   - vars/secrets.yml
  tasks:
    - name: Create superuser
      command: "docker exec {{uh_domain}} /opt/app-venv/bin/python /opt/app/manage.py createsuperuser --username admin --email {{admin_email}} --noinput"
