# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_squashed_0019_auto_20160905_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('RETRY', 'RETRY'), ('STARTED', 'STARTED')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
