# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('RECEIVED', 'RECEIVED'), ('REVOKED', 'REVOKED'), ('RETRY', 'RETRY'), ('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
