# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0002_auto_20160809_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('SUCCESS', 'SUCCESS'), ('REVOKED', 'REVOKED'), ('RETRY', 'RETRY'), ('STARTED', 'STARTED'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
