# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0005_auto_20160811_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('RECEIVED', 'RECEIVED'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('SUCCESS', 'SUCCESS'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
