# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0005_auto_20160816_1738'),
        ('djcelery', '0006_auto_20160812_1641'),
    ]

    operations = [
    ]
