# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0007_auto_20160817_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('REVOKED', 'REVOKED'), ('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS'), ('RETRY', 'RETRY')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
