# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('RETRY', 'RETRY'), ('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('REVOKED', 'REVOKED'), ('RECEIVED', 'RECEIVED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
