# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0008_auto_20160816_1755'),
        ('djcelery', '0008_auto_20160817_1631'),
    ]

    operations = [
    ]
