# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0008_auto_20160817_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('RETRY', 'RETRY'), ('RECEIVED', 'RECEIVED'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
