# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('PENDING', 'PENDING'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
