# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0011_auto_20160822_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('RECEIVED', 'RECEIVED'), ('SUCCESS', 'SUCCESS'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('FAILURE', 'FAILURE'), ('PENDING', 'PENDING')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
