# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0011_auto_20160822_1852'),
        ('djcelery', '0009_auto_20160823_2219'),
    ]

    operations = [
    ]
