# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0012_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('RECEIVED', 'RECEIVED'), ('REVOKED', 'REVOKED'), ('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
