# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0012_auto_20160826_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RETRY', 'RETRY'), ('RECEIVED', 'RECEIVED'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
