# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0013_auto_20160825_0000'),
        ('djcelery', '0013_auto_20160826_2038'),
    ]

    operations = [
    ]
