# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('RETRY', 'RETRY')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
