# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0015_auto_20160905_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REVOKED', 'REVOKED'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
